
package ws.bllClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BllWsService", targetNamespace = "http://schneider.com/bll/ws/", wsdlLocation = "file:/C:/Code%20Stuff/Java17-SOAP-Consumer/soap-consumer/src/main/resources/wsdl/BllWsService.wsdl")
public class BllWsService
    extends Service
{

    private final static URL BLLWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BLLWSSERVICE_EXCEPTION;
    private final static QName BLLWSSERVICE_QNAME = new QName("http://schneider.com/bll/ws/", "BllWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Code%20Stuff/Java17-SOAP-Consumer/soap-consumer/src/main/resources/wsdl/BllWsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BLLWSSERVICE_WSDL_LOCATION = url;
        BLLWSSERVICE_EXCEPTION = e;
    }

    public BllWsService() {
        super(__getWsdlLocation(), BLLWSSERVICE_QNAME);
    }

    public BllWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BLLWSSERVICE_QNAME, features);
    }

    public BllWsService(URL wsdlLocation) {
        super(wsdlLocation, BLLWSSERVICE_QNAME);
    }

    public BllWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BLLWSSERVICE_QNAME, features);
    }

    public BllWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BllWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BllWs
     */
    @WebEndpoint(name = "BllWsPort")
    public BllWs getBllWsPort() {
        return super.getPort(new QName("http://schneider.com/bll/ws/", "BllWsPort"), BllWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BllWs
     */
    @WebEndpoint(name = "BllWsPort")
    public BllWs getBllWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schneider.com/bll/ws/", "BllWsPort"), BllWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BLLWSSERVICE_EXCEPTION!= null) {
            throw BLLWSSERVICE_EXCEPTION;
        }
        return BLLWSSERVICE_WSDL_LOCATION;
    }

}
