
package ws.psmClasses;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IPsmConfigurationService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPsmConfigurationService {


    /**
     * 
     * @param database
     * @param configurableId
     * @param language
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationConfigurationEngineFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationDataFormatterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfiguration", action = "http://tempuri.org/IPsmConfigurationService/StartConfiguration")
    @WebResult(name = "StartConfigurationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfiguration", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfiguration")
    @ResponseWrapper(localName = "StartConfigurationResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationResponse")
    public PsmConfigurationSession startConfiguration(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language)
        throws IPsmConfigurationServiceStartConfigurationConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param database
     * @param configurableId
     * @param language
     * @param layoutBehaviourType
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationWithSpecificBehaviourDataFormatterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationWithSpecificBehaviour", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationWithSpecificBehaviour")
    @WebResult(name = "StartConfigurationWithSpecificBehaviourResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationWithSpecificBehaviour", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationWithSpecificBehaviour")
    @ResponseWrapper(localName = "StartConfigurationWithSpecificBehaviourResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationWithSpecificBehaviourResponse")
    public PsmConfigurationSession startConfigurationWithSpecificBehaviour(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language,
        @WebParam(name = "layoutBehaviourType", targetNamespace = "http://tempuri.org/")
        PsmLayoutBehaviourTypes layoutBehaviourType)
        throws IPsmConfigurationServiceStartConfigurationWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationWithSpecificBehaviourDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param database
     * @param configurableId
     * @param language
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationPermissiveModeInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationPermissiveModeConfigurationEngineFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationPermissiveModeDataFormatterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationPermissiveMode", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationPermissiveMode")
    @WebResult(name = "StartConfigurationPermissiveModeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationPermissiveMode", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationPermissiveMode")
    @ResponseWrapper(localName = "StartConfigurationPermissiveModeResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationPermissiveModeResponse")
    public PsmConfigurationSession startConfigurationPermissiveMode(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language)
        throws IPsmConfigurationServiceStartConfigurationPermissiveModeConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationPermissiveModeDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationPermissiveModeInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param database
     * @param configurableId
     * @param language
     * @param layoutBehaviourType
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationPermissiveModeWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationPermissiveModeWithSpecificBehaviourDataFormatterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationPermissiveModeWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationPermissiveModeWithSpecificBehaviour", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationPermissiveModeWithSpecificBehaviour")
    @WebResult(name = "StartConfigurationPermissiveModeWithSpecificBehaviourResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationPermissiveModeWithSpecificBehaviour", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationPermissiveModeWithSpecificBehaviour")
    @ResponseWrapper(localName = "StartConfigurationPermissiveModeWithSpecificBehaviourResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationPermissiveModeWithSpecificBehaviourResponse")
    public PsmConfigurationSession startConfigurationPermissiveModeWithSpecificBehaviour(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language,
        @WebParam(name = "layoutBehaviourType", targetNamespace = "http://tempuri.org/")
        PsmLayoutBehaviourTypes layoutBehaviourType)
        throws IPsmConfigurationServiceStartConfigurationPermissiveModeWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationPermissiveModeWithSpecificBehaviourDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationPermissiveModeWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param reference
     * @param database
     * @param configurableId
     * @param language
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationFromReferenceInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferenceDataFormatterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferenceConfigurationEngineFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationFromReference", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationFromReference")
    @WebResult(name = "StartConfigurationFromReferenceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationFromReference", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReference")
    @ResponseWrapper(localName = "StartConfigurationFromReferenceResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferenceResponse")
    public PsmConfigurationSession startConfigurationFromReference(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "reference", targetNamespace = "http://tempuri.org/")
        String reference,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language)
        throws IPsmConfigurationServiceStartConfigurationFromReferenceConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferenceDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferenceInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param reference
     * @param database
     * @param configurableId
     * @param language
     * @param layoutBehaviourType
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationFromReferenceWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferenceWithSpecificBehaviourDataFormatterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferenceWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationFromReferenceWithSpecificBehaviour", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationFromReferenceWithSpecificBehaviour")
    @WebResult(name = "StartConfigurationFromReferenceWithSpecificBehaviourResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationFromReferenceWithSpecificBehaviour", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferenceWithSpecificBehaviour")
    @ResponseWrapper(localName = "StartConfigurationFromReferenceWithSpecificBehaviourResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferenceWithSpecificBehaviourResponse")
    public PsmConfigurationSession startConfigurationFromReferenceWithSpecificBehaviour(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "reference", targetNamespace = "http://tempuri.org/")
        String reference,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language,
        @WebParam(name = "layoutBehaviourType", targetNamespace = "http://tempuri.org/")
        PsmLayoutBehaviourTypes layoutBehaviourType)
        throws IPsmConfigurationServiceStartConfigurationFromReferenceWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferenceWithSpecificBehaviourDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferenceWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param reference
     * @param database
     * @param configurableId
     * @param language
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeConfigurationEngineFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeDataFormatterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationFromReferencePermissiveMode", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationFromReferencePermissiveMode")
    @WebResult(name = "StartConfigurationFromReferencePermissiveModeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationFromReferencePermissiveMode", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferencePermissiveMode")
    @ResponseWrapper(localName = "StartConfigurationFromReferencePermissiveModeResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferencePermissiveModeResponse")
    public PsmConfigurationSession startConfigurationFromReferencePermissiveMode(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "reference", targetNamespace = "http://tempuri.org/")
        String reference,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language)
        throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param reference
     * @param database
     * @param configurableId
     * @param language
     * @param layoutBehaviourType
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeWithSpecificBehaviourDataFormatterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage
     */
    @WebMethod(operationName = "StartConfigurationFromReferencePermissiveModeWithSpecificBehaviour", action = "http://tempuri.org/IPsmConfigurationService/StartConfigurationFromReferencePermissiveModeWithSpecificBehaviour")
    @WebResult(name = "StartConfigurationFromReferencePermissiveModeWithSpecificBehaviourResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartConfigurationFromReferencePermissiveModeWithSpecificBehaviour", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferencePermissiveModeWithSpecificBehaviour")
    @ResponseWrapper(localName = "StartConfigurationFromReferencePermissiveModeWithSpecificBehaviourResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.StartConfigurationFromReferencePermissiveModeWithSpecificBehaviourResponse")
    public PsmConfigurationSession startConfigurationFromReferencePermissiveModeWithSpecificBehaviour(
        @WebParam(name = "configurableId", targetNamespace = "http://tempuri.org/")
        String configurableId,
        @WebParam(name = "reference", targetNamespace = "http://tempuri.org/")
        String reference,
        @WebParam(name = "database", targetNamespace = "http://tempuri.org/")
        String database,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language,
        @WebParam(name = "layoutBehaviourType", targetNamespace = "http://tempuri.org/")
        PsmLayoutBehaviourTypes layoutBehaviourType)
        throws IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeWithSpecificBehaviourConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeWithSpecificBehaviourDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceStartConfigurationFromReferencePermissiveModeWithSpecificBehaviourInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param configurationSessionId
     * @param values
     * @param characteristicId
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceSetCharacteristicValuesConfigurationEngineFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceSetCharacteristicValuesDataFormatterFaultFaultFaultMessage
     * @throws IPsmConfigurationServiceSetCharacteristicValuesInvalidParameterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetCharacteristicValues", action = "http://tempuri.org/IPsmConfigurationService/SetCharacteristicValues")
    @WebResult(name = "SetCharacteristicValuesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetCharacteristicValues", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.SetCharacteristicValues")
    @ResponseWrapper(localName = "SetCharacteristicValuesResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.SetCharacteristicValuesResponse")
    public PsmConfigurationSession setCharacteristicValues(
        @WebParam(name = "configurationSessionId", targetNamespace = "http://tempuri.org/")
        Integer configurationSessionId,
        @WebParam(name = "characteristicId", targetNamespace = "http://tempuri.org/")
        String characteristicId,
        @WebParam(name = "values", targetNamespace = "http://tempuri.org/")
        ArrayOfstring values)
        throws IPsmConfigurationServiceSetCharacteristicValuesConfigurationEngineFaultFaultFaultMessage, IPsmConfigurationServiceSetCharacteristicValuesDataFormatterFaultFaultFaultMessage, IPsmConfigurationServiceSetCharacteristicValuesInvalidParameterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param configurationSessionId
     * @return
     *     returns ws.psmClasses.PsmConfigurationSession
     * @throws IPsmConfigurationServiceGetConfigurationDataFormatterFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetConfiguration", action = "http://tempuri.org/IPsmConfigurationService/GetConfiguration")
    @WebResult(name = "GetConfigurationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.GetConfigurationResponse")
    public PsmConfigurationSession getConfiguration(
        @WebParam(name = "configurationSessionId", targetNamespace = "http://tempuri.org/")
        Integer configurationSessionId)
        throws IPsmConfigurationServiceGetConfigurationDataFormatterFaultFaultFaultMessage
    ;

    /**
     * 
     * @param configurationSessionId
     */
    @WebMethod(operationName = "DeleteConfiguration", action = "http://tempuri.org/IPsmConfigurationService/DeleteConfiguration")
    @RequestWrapper(localName = "DeleteConfiguration", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.DeleteConfiguration")
    @ResponseWrapper(localName = "DeleteConfigurationResponse", targetNamespace = "http://tempuri.org/", className = "ws.psmClasses.DeleteConfigurationResponse")
    public void deleteConfiguration(
        @WebParam(name = "configurationSessionId", targetNamespace = "http://tempuri.org/")
        Integer configurationSessionId);

}
