//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.23 at 11:18:29 AM IST 
//


package schemas.response;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hier"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="hiernode"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="icon" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="posnr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HiveInstances"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="instance" type="{}instance" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="node" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="csticGroup" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence minOccurs="0"&gt;
 *                             &lt;element name="cstic" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="csticValueStatus" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                               &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                               &lt;attribute name="isDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                               &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                               &lt;attribute name="img" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="hasDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="isConflicting" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="isMultiValued" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="isReadOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="qty" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                                     &lt;attribute name="intervalMin" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                                     &lt;attribute name="intervalMax" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                                     &lt;attribute name="entryMask" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="freeEntry" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="isExpanded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="isComplete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="displayParent" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="isComplete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="isConflicting" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="isGhost" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="parentId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                 &lt;attribute name="qty" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="unsetCstics"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="unsetCstic" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="alias_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="configId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="du_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="du_status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="hasGlobalGroups" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="kb_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="project_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="scope" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="country" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sscVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hier",
    "hiveInstances",
    "node",
    "unsetCstics"
})
@XmlRootElement(name = "nodes")
public class Nodes {

    @XmlElement(required = true)
    protected Nodes.Hier hier;
    @XmlElement(name = "HiveInstances", required = true)
    protected Nodes.HiveInstances hiveInstances;
    @XmlElement(required = true)
    protected List<Nodes.Node> node;
    @XmlElement(required = true)
    protected Nodes.UnsetCstics unsetCstics;
    @XmlAttribute(name = "alias_id", required = true)
    protected String aliasId;
    @XmlAttribute(name = "configId", required = true)
    protected String configId;
    @XmlAttribute(name = "du_id", required = true)
    protected String duId;
    @XmlAttribute(name = "du_status", required = true)
    protected String duStatus;
    @XmlAttribute(name = "hasGlobalGroups", required = true)
    protected String hasGlobalGroups;
    @XmlAttribute(name = "kb_id", required = true)
    protected String kbId;
    @XmlAttribute(name = "language", required = true)
    protected String language;
    @XmlAttribute(name = "project_id", required = true)
    protected String projectId;
    @XmlAttribute(name = "scope", required = true)
    protected String scope;
    @XmlAttribute(name = "country", required = true)
    protected String country;
    @XmlAttribute(name = "sscVersion", required = true)
    protected String sscVersion;

    /**
     * Gets the value of the hier property.
     * 
     * @return
     *     possible object is
     *     {@link Nodes.Hier }
     *     
     */
    public Nodes.Hier getHier() {
        return hier;
    }

    /**
     * Sets the value of the hier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nodes.Hier }
     *     
     */
    public void setHier(Nodes.Hier value) {
        this.hier = value;
    }

    /**
     * Gets the value of the hiveInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Nodes.HiveInstances }
     *     
     */
    public Nodes.HiveInstances getHiveInstances() {
        return hiveInstances;
    }

    /**
     * Sets the value of the hiveInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nodes.HiveInstances }
     *     
     */
    public void setHiveInstances(Nodes.HiveInstances value) {
        this.hiveInstances = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nodes.Node }
     * 
     * 
     */
    public List<Nodes.Node> getNode() {
        if (node == null) {
            node = new ArrayList<Nodes.Node>();
        }
        return this.node;
    }

    /**
     * Gets the value of the unsetCstics property.
     * 
     * @return
     *     possible object is
     *     {@link Nodes.UnsetCstics }
     *     
     */
    public Nodes.UnsetCstics getUnsetCstics() {
        return unsetCstics;
    }

    /**
     * Sets the value of the unsetCstics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nodes.UnsetCstics }
     *     
     */
    public void setUnsetCstics(Nodes.UnsetCstics value) {
        this.unsetCstics = value;
    }

    /**
     * Gets the value of the aliasId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasId() {
        return aliasId;
    }

    /**
     * Sets the value of the aliasId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasId(String value) {
        this.aliasId = value;
    }

    /**
     * Gets the value of the configId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * Sets the value of the configId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigId(String value) {
        this.configId = value;
    }

    /**
     * Gets the value of the duId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuId() {
        return duId;
    }

    /**
     * Sets the value of the duId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuId(String value) {
        this.duId = value;
    }

    /**
     * Gets the value of the duStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuStatus() {
        return duStatus;
    }

    /**
     * Sets the value of the duStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuStatus(String value) {
        this.duStatus = value;
    }

    /**
     * Gets the value of the hasGlobalGroups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasGlobalGroups() {
        return hasGlobalGroups;
    }

    /**
     * Sets the value of the hasGlobalGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasGlobalGroups(String value) {
        this.hasGlobalGroups = value;
    }

    /**
     * Gets the value of the kbId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKbId() {
        return kbId;
    }

    /**
     * Sets the value of the kbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKbId(String value) {
        this.kbId = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the projectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * Sets the value of the projectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectId(String value) {
        this.projectId = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the sscVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSscVersion() {
        return sscVersion;
    }

    /**
     * Sets the value of the sscVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSscVersion(String value) {
        this.sscVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="hiernode"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="icon" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="posnr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hiernode"
    })
    public static class Hier {

        @XmlElement(required = true)
        protected Nodes.Hier.Hiernode hiernode;

        /**
         * Gets the value of the hiernode property.
         * 
         * @return
         *     possible object is
         *     {@link Nodes.Hier.Hiernode }
         *     
         */
        public Nodes.Hier.Hiernode getHiernode() {
            return hiernode;
        }

        /**
         * Sets the value of the hiernode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Nodes.Hier.Hiernode }
         *     
         */
        public void setHiernode(Nodes.Hier.Hiernode value) {
            this.hiernode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="icon" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="posnr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Hiernode {

            @XmlAttribute(name = "bompath", required = true)
            protected String bompath;
            @XmlAttribute(name = "desc", required = true)
            protected String desc;
            @XmlAttribute(name = "icon", required = true)
            protected String icon;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "posnr", required = true)
            protected String posnr;

            /**
             * Gets the value of the bompath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBompath() {
                return bompath;
            }

            /**
             * Sets the value of the bompath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBompath(String value) {
                this.bompath = value;
            }

            /**
             * Gets the value of the desc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesc() {
                return desc;
            }

            /**
             * Sets the value of the desc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesc(String value) {
                this.desc = value;
            }

            /**
             * Gets the value of the icon property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIcon() {
                return icon;
            }

            /**
             * Sets the value of the icon property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIcon(String value) {
                this.icon = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the posnr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosnr() {
                return posnr;
            }

            /**
             * Sets the value of the posnr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosnr(String value) {
                this.posnr = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="instance" type="{}instance" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instance"
    })
    public static class HiveInstances {

        @XmlElement(required = true)
        protected List<Instance> instance;

        /**
         * Gets the value of the instance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the instance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Instance }
         * 
         * 
         */
        public List<Instance> getInstance() {
            if (instance == null) {
                instance = new ArrayList<Instance>();
            }
            return this.instance;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="csticGroup" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence minOccurs="0"&gt;
     *                   &lt;element name="cstic" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="csticValueStatus" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                     &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                                     &lt;attribute name="isDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                                     &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                     &lt;attribute name="img" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="hasDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="isConflicting" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="isMultiValued" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="isReadOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="qty" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                           &lt;attribute name="intervalMin" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *                           &lt;attribute name="intervalMax" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *                           &lt;attribute name="entryMask" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="freeEntry" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="isExpanded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="isComplete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="displayParent" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="isComplete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="isConflicting" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="isGhost" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="parentId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *       &lt;attribute name="qty" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "csticGroup"
    })
    public static class Node {

        @XmlElement(required = true)
        protected List<Nodes.Node.CsticGroup> csticGroup;
        @XmlAttribute(name = "bompath", required = true)
        protected String bompath;
        @XmlAttribute(name = "desc", required = true)
        protected String desc;
        @XmlAttribute(name = "displayParent", required = true)
        protected boolean displayParent;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "isComplete", required = true)
        protected boolean isComplete;
        @XmlAttribute(name = "isConflicting", required = true)
        protected boolean isConflicting;
        @XmlAttribute(name = "isGhost", required = true)
        protected boolean isGhost;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "parentId", required = true)
        protected String parentId;
        @XmlAttribute(name = "position", required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short position;
        @XmlAttribute(name = "qty", required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short qty;

        /**
         * Gets the value of the csticGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the csticGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCsticGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nodes.Node.CsticGroup }
         * 
         * 
         */
        public List<Nodes.Node.CsticGroup> getCsticGroup() {
            if (csticGroup == null) {
                csticGroup = new ArrayList<Nodes.Node.CsticGroup>();
            }
            return this.csticGroup;
        }

        /**
         * Gets the value of the bompath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBompath() {
            return bompath;
        }

        /**
         * Sets the value of the bompath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBompath(String value) {
            this.bompath = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

        /**
         * Gets the value of the displayParent property.
         * 
         */
        public boolean isDisplayParent() {
            return displayParent;
        }

        /**
         * Sets the value of the displayParent property.
         * 
         */
        public void setDisplayParent(boolean value) {
            this.displayParent = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the isComplete property.
         * 
         */
        public boolean isIsComplete() {
            return isComplete;
        }

        /**
         * Sets the value of the isComplete property.
         * 
         */
        public void setIsComplete(boolean value) {
            this.isComplete = value;
        }

        /**
         * Gets the value of the isConflicting property.
         * 
         */
        public boolean isIsConflicting() {
            return isConflicting;
        }

        /**
         * Sets the value of the isConflicting property.
         * 
         */
        public void setIsConflicting(boolean value) {
            this.isConflicting = value;
        }

        /**
         * Gets the value of the isGhost property.
         * 
         */
        public boolean isIsGhost() {
            return isGhost;
        }

        /**
         * Sets the value of the isGhost property.
         * 
         */
        public void setIsGhost(boolean value) {
            this.isGhost = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the parentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentId() {
            return parentId;
        }

        /**
         * Sets the value of the parentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentId(String value) {
            this.parentId = value;
        }

        /**
         * Gets the value of the position property.
         * 
         */
        public short getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         */
        public void setPosition(short value) {
            this.position = value;
        }

        /**
         * Gets the value of the qty property.
         * 
         */
        public short getQty() {
            return qty;
        }

        /**
         * Sets the value of the qty property.
         * 
         */
        public void setQty(short value) {
            this.qty = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence minOccurs="0"&gt;
         *         &lt;element name="cstic" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="csticValueStatus" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                           &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                           &lt;attribute name="isDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                           &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                           &lt;attribute name="img" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="hasDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="isConflicting" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="isMultiValued" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="isReadOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="qty" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *                 &lt;attribute name="intervalMin" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *                 &lt;attribute name="intervalMax" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *                 &lt;attribute name="entryMask" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="freeEntry" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="isExpanded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="isComplete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cstic"
        })
        public static class CsticGroup {

            protected List<Nodes.Node.CsticGroup.Cstic> cstic;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "isExpanded", required = true)
            protected boolean isExpanded;
            @XmlAttribute(name = "isVisible", required = true)
            protected boolean isVisible;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "group", required = true)
            protected String group;
            @XmlAttribute(name = "isComplete", required = true)
            protected boolean isComplete;

            /**
             * Gets the value of the cstic property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the cstic property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCstic().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Nodes.Node.CsticGroup.Cstic }
             * 
             * 
             */
            public List<Nodes.Node.CsticGroup.Cstic> getCstic() {
                if (cstic == null) {
                    cstic = new ArrayList<Nodes.Node.CsticGroup.Cstic>();
                }
                return this.cstic;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the isExpanded property.
             * 
             */
            public boolean isIsExpanded() {
                return isExpanded;
            }

            /**
             * Sets the value of the isExpanded property.
             * 
             */
            public void setIsExpanded(boolean value) {
                this.isExpanded = value;
            }

            /**
             * Gets the value of the isVisible property.
             * 
             */
            public boolean isIsVisible() {
                return isVisible;
            }

            /**
             * Sets the value of the isVisible property.
             * 
             */
            public void setIsVisible(boolean value) {
                this.isVisible = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the group property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGroup() {
                return group;
            }

            /**
             * Sets the value of the group property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGroup(String value) {
                this.group = value;
            }

            /**
             * Gets the value of the isComplete property.
             * 
             */
            public boolean isIsComplete() {
                return isComplete;
            }

            /**
             * Sets the value of the isComplete property.
             * 
             */
            public void setIsComplete(boolean value) {
                this.isComplete = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="csticValueStatus" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *                 &lt;attribute name="isDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *                 &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                 &lt;attribute name="img" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="hasDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="isConflicting" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="isMultiValued" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="isReadOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="isVisible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="qty" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
             *       &lt;attribute name="intervalMin" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
             *       &lt;attribute name="intervalMax" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
             *       &lt;attribute name="entryMask" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="freeEntry" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "desc",
                "name",
                "csticValueStatus"
            })
            public static class Cstic {

                protected String desc;
                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected List<Nodes.Node.CsticGroup.Cstic.CsticValueStatus> csticValueStatus;
                @XmlAttribute(name = "bompath", required = true)
                protected String bompath;
                @XmlAttribute(name = "hasDefault", required = true)
                protected boolean hasDefault;
                @XmlAttribute(name = "id", required = true)
                protected String id;
                @XmlAttribute(name = "isAssigned", required = true)
                protected boolean isAssigned;
                @XmlAttribute(name = "isConflicting", required = true)
                protected boolean isConflicting;
                @XmlAttribute(name = "isMultiValued", required = true)
                protected boolean isMultiValued;
                @XmlAttribute(name = "isReadOnly", required = true)
                protected boolean isReadOnly;
                @XmlAttribute(name = "isRequired", required = true)
                protected boolean isRequired;
                @XmlAttribute(name = "isVisible", required = true)
                protected boolean isVisible;
                @XmlAttribute(name = "unit", required = true)
                protected String unit;
                @XmlAttribute(name = "qty")
                @XmlSchemaType(name = "unsignedByte")
                protected Short qty;
                @XmlAttribute(name = "intervalMin")
                protected BigDecimal intervalMin;
                @XmlAttribute(name = "intervalMax")
                protected BigDecimal intervalMax;
                @XmlAttribute(name = "entryMask")
                protected String entryMask;
                @XmlAttribute(name = "type")
                protected String type;
                @XmlAttribute(name = "freeEntry")
                protected Boolean freeEntry;

                /**
                 * Gets the value of the desc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDesc() {
                    return desc;
                }

                /**
                 * Sets the value of the desc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDesc(String value) {
                    this.desc = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the csticValueStatus property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the csticValueStatus property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCsticValueStatus().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Nodes.Node.CsticGroup.Cstic.CsticValueStatus }
                 * 
                 * 
                 */
                public List<Nodes.Node.CsticGroup.Cstic.CsticValueStatus> getCsticValueStatus() {
                    if (csticValueStatus == null) {
                        csticValueStatus = new ArrayList<Nodes.Node.CsticGroup.Cstic.CsticValueStatus>();
                    }
                    return this.csticValueStatus;
                }

                /**
                 * Gets the value of the bompath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBompath() {
                    return bompath;
                }

                /**
                 * Sets the value of the bompath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBompath(String value) {
                    this.bompath = value;
                }

                /**
                 * Gets the value of the hasDefault property.
                 * 
                 */
                public boolean isHasDefault() {
                    return hasDefault;
                }

                /**
                 * Sets the value of the hasDefault property.
                 * 
                 */
                public void setHasDefault(boolean value) {
                    this.hasDefault = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the isAssigned property.
                 * 
                 */
                public boolean isIsAssigned() {
                    return isAssigned;
                }

                /**
                 * Sets the value of the isAssigned property.
                 * 
                 */
                public void setIsAssigned(boolean value) {
                    this.isAssigned = value;
                }

                /**
                 * Gets the value of the isConflicting property.
                 * 
                 */
                public boolean isIsConflicting() {
                    return isConflicting;
                }

                /**
                 * Sets the value of the isConflicting property.
                 * 
                 */
                public void setIsConflicting(boolean value) {
                    this.isConflicting = value;
                }

                /**
                 * Gets the value of the isMultiValued property.
                 * 
                 */
                public boolean isIsMultiValued() {
                    return isMultiValued;
                }

                /**
                 * Sets the value of the isMultiValued property.
                 * 
                 */
                public void setIsMultiValued(boolean value) {
                    this.isMultiValued = value;
                }

                /**
                 * Gets the value of the isReadOnly property.
                 * 
                 */
                public boolean isIsReadOnly() {
                    return isReadOnly;
                }

                /**
                 * Sets the value of the isReadOnly property.
                 * 
                 */
                public void setIsReadOnly(boolean value) {
                    this.isReadOnly = value;
                }

                /**
                 * Gets the value of the isRequired property.
                 * 
                 */
                public boolean isIsRequired() {
                    return isRequired;
                }

                /**
                 * Sets the value of the isRequired property.
                 * 
                 */
                public void setIsRequired(boolean value) {
                    this.isRequired = value;
                }

                /**
                 * Gets the value of the isVisible property.
                 * 
                 */
                public boolean isIsVisible() {
                    return isVisible;
                }

                /**
                 * Sets the value of the isVisible property.
                 * 
                 */
                public void setIsVisible(boolean value) {
                    this.isVisible = value;
                }

                /**
                 * Gets the value of the unit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

                /**
                 * Gets the value of the qty property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getQty() {
                    return qty;
                }

                /**
                 * Sets the value of the qty property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setQty(Short value) {
                    this.qty = value;
                }

                /**
                 * Gets the value of the intervalMin property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getIntervalMin() {
                    return intervalMin;
                }

                /**
                 * Sets the value of the intervalMin property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setIntervalMin(BigDecimal value) {
                    this.intervalMin = value;
                }

                /**
                 * Gets the value of the intervalMax property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getIntervalMax() {
                    return intervalMax;
                }

                /**
                 * Sets the value of the intervalMax property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setIntervalMax(BigDecimal value) {
                    this.intervalMax = value;
                }

                /**
                 * Gets the value of the entryMask property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEntryMask() {
                    return entryMask;
                }

                /**
                 * Sets the value of the entryMask property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEntryMask(String value) {
                    this.entryMask = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the freeEntry property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isFreeEntry() {
                    return freeEntry;
                }

                /**
                 * Sets the value of the freeEntry property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setFreeEntry(Boolean value) {
                    this.freeEntry = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="isAssigned" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
                 *       &lt;attribute name="isDefault" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
                 *       &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *       &lt;attribute name="img" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name"
                })
                public static class CsticValueStatus {

                    @XmlElement(required = true)
                    protected String name;
                    @XmlAttribute(name = "isAssigned", required = true)
                    protected boolean isAssigned;
                    @XmlAttribute(name = "isDefault", required = true)
                    protected boolean isDefault;
                    @XmlAttribute(name = "valueId", required = true)
                    protected String valueId;
                    @XmlAttribute(name = "img")
                    protected String img;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the isAssigned property.
                     * 
                     */
                    public boolean isIsAssigned() {
                        return isAssigned;
                    }

                    /**
                     * Sets the value of the isAssigned property.
                     * 
                     */
                    public void setIsAssigned(boolean value) {
                        this.isAssigned = value;
                    }

                    /**
                     * Gets the value of the isDefault property.
                     * 
                     */
                    public boolean isIsDefault() {
                        return isDefault;
                    }

                    /**
                     * Sets the value of the isDefault property.
                     * 
                     */
                    public void setIsDefault(boolean value) {
                        this.isDefault = value;
                    }

                    /**
                     * Gets the value of the valueId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValueId() {
                        return valueId;
                    }

                    /**
                     * Sets the value of the valueId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValueId(String value) {
                        this.valueId = value;
                    }

                    /**
                     * Gets the value of the img property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getImg() {
                        return img;
                    }

                    /**
                     * Sets the value of the img property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setImg(String value) {
                        this.img = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="unsetCstic" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unsetCstic"
    })
    public static class UnsetCstics {

        protected List<Nodes.UnsetCstics.UnsetCstic> unsetCstic;

        /**
         * Gets the value of the unsetCstic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the unsetCstic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnsetCstic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nodes.UnsetCstics.UnsetCstic }
         * 
         * 
         */
        public List<Nodes.UnsetCstics.UnsetCstic> getUnsetCstic() {
            if (unsetCstic == null) {
                unsetCstic = new ArrayList<Nodes.UnsetCstics.UnsetCstic>();
            }
            return this.unsetCstic;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="bompath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="valueId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class UnsetCstic {

            @XmlAttribute(name = "bompath", required = true)
            protected String bompath;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "valueId", required = true)
            protected String valueId;

            /**
             * Gets the value of the bompath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBompath() {
                return bompath;
            }

            /**
             * Sets the value of the bompath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBompath(String value) {
                this.bompath = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the valueId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValueId() {
                return valueId;
            }

            /**
             * Sets the value of the valueId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValueId(String value) {
                this.valueId = value;
            }

        }

    }

}
