//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.23 at 11:18:29 AM IST 
//


package schemas.response;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schemas.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schemas.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nodes }
     * 
     */
    public Nodes createNodes() {
        return new Nodes();
    }

    /**
     * Create an instance of {@link Nodes.UnsetCstics }
     * 
     */
    public Nodes.UnsetCstics createNodesUnsetCstics() {
        return new Nodes.UnsetCstics();
    }

    /**
     * Create an instance of {@link Nodes.Node }
     * 
     */
    public Nodes.Node createNodesNode() {
        return new Nodes.Node();
    }

    /**
     * Create an instance of {@link Nodes.Node.CsticGroup }
     * 
     */
    public Nodes.Node.CsticGroup createNodesNodeCsticGroup() {
        return new Nodes.Node.CsticGroup();
    }

    /**
     * Create an instance of {@link Nodes.Node.CsticGroup.Cstic }
     * 
     */
    public Nodes.Node.CsticGroup.Cstic createNodesNodeCsticGroupCstic() {
        return new Nodes.Node.CsticGroup.Cstic();
    }

    /**
     * Create an instance of {@link Nodes.Hier }
     * 
     */
    public Nodes.Hier createNodesHier() {
        return new Nodes.Hier();
    }

    /**
     * Create an instance of {@link Nodes.HiveInstances }
     * 
     */
    public Nodes.HiveInstances createNodesHiveInstances() {
        return new Nodes.HiveInstances();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Nodes.UnsetCstics.UnsetCstic }
     * 
     */
    public Nodes.UnsetCstics.UnsetCstic createNodesUnsetCsticsUnsetCstic() {
        return new Nodes.UnsetCstics.UnsetCstic();
    }

    /**
     * Create an instance of {@link Nodes.Node.CsticGroup.Cstic.CsticValueStatus }
     * 
     */
    public Nodes.Node.CsticGroup.Cstic.CsticValueStatus createNodesNodeCsticGroupCsticCsticValueStatus() {
        return new Nodes.Node.CsticGroup.Cstic.CsticValueStatus();
    }

    /**
     * Create an instance of {@link Nodes.Hier.Hiernode }
     * 
     */
    public Nodes.Hier.Hiernode createNodesHierHiernode() {
        return new Nodes.Hier.Hiernode();
    }

}
